package model;

public enum EmployeeType {
    HR_EMPLOYEE,
    CUSTOMER_SERVICE,
    SENIOR_CUSTOMER_SERVICE,
    FINANCIAL_MANAGER,
    ADMINISTRATION_MANAGER,
    PRODUCTION_MANAGER,
    SERVICE_MANAGER
}
